
all: graph.o list.o sort.o
	gcc -g -Wall -o task3.out graph.o list.o sort.o

sort.o:
	gcc -g -Wall -c -o sort.o sort.c

list.o: list.c
	gcc -g -Wall -c -o list.o list.c

graph.o: graph.c
	gcc -g -Wall -c -o graph.o graph.c


