ls:
	gcc -g -Wall ls.c -o ls.out

od:
	gcc -g -Wall od.c -o od.out

pwd:
	gcc -g -Wall pwd.c -o pwd.out

echo:
	gcc -g -Wall echo.c -o echo.out

cmp:
	gcc -g -Wall cmp.c -o cmp.out

ln:
	gcc -g -Wall ln.c -o ln.out
	
all:
	gcc -g -Wall ls.c -o ls.out	
	gcc -g -Wall od.c -o od.out
	gcc -g -Wall pwd.c -o pwd.out
	gcc -g -Wall echo.c -o echo.out
	gcc -g -Wall cmp.c -o cmp.out
	gcc -g -Wall ln.c -o ln.out

	
clean:
	rm *.out
	