ls:
	gcc -g -Wall ls.c -o ls.out

od:
	gcc -g -Wall od.c -o od.out

pwd:
	gcc -g -Wall pwd.c -o pwd.out

echo:
	gcc -g -Wall echo.c -o echo.out

cmp:
	gcc -g -Wall cmp.c -o cmp.out

clean:
	rm *.out
	