//this module prints syntax tree generated by syntax tree builder (located in syntax_tree.c)


#include <stdio.h>
#include "syntax_tree_types.h"

// cmd_tree_root - not NULL link that points at the root of syntax tree

void print_syntax_tree(cmd_link cmd_tree_root){
    cmd_link cmd = cmd_tree_root;

    printf("\n");
    while (cmd!=NULL){

        if (cmd->separator!=NULL){
            printf("%s ",cmd->separator);
        }

        else{
            printf("NULL ");
        }

        cmd = cmd->next;
    }
    printf("\n");

    return;
}